echo Building the backend...
docker build -t covbot/backend backend/
echo Building the corenlp server...
docker build -t covbot/corenlp corenlp/
echo Building the frontend...
docker build -t covbot/frontend frontend/
echo Done!
