echo Building the backend...
docker build -t backend backend/
echo Building the corenlp server...
docker build -t corenlp corenlp/
echo Building the frontend...
docker build -t frontend frontend/
echo Done!
