version: "3.8"

services:
  backend:
    image: backend
    volumes:
      - logs:/usr/src/app/logs
    ports:
      - 5200:5200
  corenlp:
    image: corenlp
    ports:
      - 9000:9000
  frontend:
    image: frontend
    ports:
      - 80:80

volumes:
  logs:
    external: false
